@startuml 深緑の密林
    '!include Config.puml
    !include https://raw.githubusercontent.com/Star-Delta/PlantUML/master/%E3%83%AB%E3%82%A4%E3%83%B3%E3%82%BA%E3%82%B7%E3%83%BC%E3%82%AB%E3%83%BC/MAP/Config.puml

    /'
    state Name {
        state "xF" as Name_xF  {
            state "横_縦" as Name_xF_横_縦
            state F_横_縦 <<Start>>
            F_横_縦 : スタート地点
            state F_横_縦 <<Monstar>>
            F_横_縦 : モンスター:*体
            state F_横_縦 <<Shop>>
            F_横_縦 : ニュイ
            state F_横_縦 <<MagicShop>>
            F_横_縦 : 魔導書店
            F_横_縦 : 壺・樽:*個
            F_横_縦 : 草:*個
            F_横_縦 : 山:*個
            F_横_縦 : 宝箱:*個
            F_横_縦 : 冒険者:*名
            F_横_縦 -up-> piyo
            F_横_縦 -right-> piyo
            F_横_縦 -down-> piyo
            F_横_縦 -left-> piyo
            F_横_縦 -[#green,thickness=5]-> [*]
        }
    }
    '/
    state 深緑の密林  {
        state "1F" as 深緑の密林_1F {
            state "1_2" as 深緑の密林_1F_1_2
            深緑の密林_1F_1_2 : 草:2個
            深緑の密林_1F_1_2 : 宝箱:1個
            深緑の密林_1F_1_2 -down->深緑の密林_1F_1_3
            深緑の密林_1F_1_2 -left->深緑の密林_1F_2_2

            state "1_3" as 深緑の密林_1F_1_3
            深緑の密林_1F_1_3 -up-> 深緑の密林_1F_1_2
            深緑の密林_1F_1_3 -down[#green,thickness=5]-> [*]
            深緑の密林_1F_1_3 -left-> 深緑の密林_1F_2_3

            state "2_2" as 深緑の密林_1F_2_2 <<Monstar>>
            深緑の密林_1F_2_2 : モンスター:4体
            深緑の密林_1F_2_2 -right->深緑の密林_1F_1_2
            深緑の密林_1F_2_2 -down[#green,thickness=5]->深緑の密林_1F_2_3
            深緑の密林_1F_2_2 -left->深緑の密林_1F_3_2

            state "2_3" as 深緑の密林_1F_2_3
            深緑の密林_1F_2_3 : 壺・樽:3個
            深緑の密林_1F_2_3 : 草:2個
            深緑の密林_1F_2_3 -up-> 深緑の密林_1F_2_2
            深緑の密林_1F_2_3 -right[#green,thickness=5]-> 深緑の密林_1F_1_3
            深緑の密林_1F_2_3 -left-> 深緑の密林_1F_3_3

            state "3_2" as 深緑の密林_1F_3_2
            深緑の密林_1F_3_2 : 壺・樽:3個
            深緑の密林_1F_3_2 : 草:4個
            深緑の密林_1F_3_2 -right[#green,thickness=5]->深緑の密林_1F_2_2
            深緑の密林_1F_3_2 -left->深緑の密林_1f_4_2

            state "3_3" as 深緑の密林_1F_3_3 <<Monstar>>
            深緑の密林_1F_3_3 : モンスター:4体
            深緑の密林_1F_3_3 -right-> 深緑の密林_1F_2_3
            深緑の密林_1F_3_3 -down-> 深緑の密林_1F_3_4
            深緑の密林_1F_3_3 -left-> 深緑の密林_1F_4_3

            state "3_4" as 深緑の密林_1F_3_4
            深緑の密林_1F_3_4 : 冒険者:2名
            深緑の密林_1F_3_4 : ※冒険者から[緑のクスリ]*3
            深緑の密林_1F_3_4 -up->深緑の密林_1F_3_3

            state "4_1" as 深緑の密林_1F_4_1 <<Start>>
            深緑の密林_1F_4_1 : スタート地点
            深緑の密林_1F_4_1 -down[#green,thickness=5]-> 深緑の密林_1f_4_2

            state "4_2" as 深緑の密林_1f_4_2 <<Monstar>>
            深緑の密林_1f_4_2 : モンスター:3体
            深緑の密林_1f_4_2 -up->深緑の密林_1F_4_1
            深緑の密林_1f_4_2 -right[#green,thickness=5]->深緑の密林_1F_3_2
            深緑の密林_1f_4_2 -down->深緑の密林_1F_4_3

            state "4_3" as 深緑の密林_1F_4_3
            深緑の密林_1F_4_3 : 壺・樽:2個
            深緑の密林_1F_4_3 : 草:1個
            深緑の密林_1F_4_3 : 宝箱:1個
            深緑の密林_1F_4_3 : ※空中のスイッチを押す
            深緑の密林_1F_4_3 -up->深緑の密林_1f_4_2
            深緑の密林_1F_4_3 -right->深緑の密林_1F_3_3

        }
        深緑の密林_1F -down-> 深緑の密林_2F

        state "2F" as 深緑の密林_2F {
            state "1_3" as 深緑の密林_2F_1_3 <<Start>>
            深緑の密林_2F_1_3 : スタート地点
            深緑の密林_2F_1_3 : 草:1個
            深緑の密林_2F_1_3 -left[#green,thickness=5]-> 深緑の密林_2F_2_3
            
            state "1_4" as 深緑の密林_2F_1_4
            深緑の密林_2F_1_4 : 壺・樽:4個
            深緑の密林_2F_1_4 : ※壺から[研究日誌の紙片1]
            深緑の密林_2F_1_4 : 草:2個

            state "2_2" as 深緑の密林_2F_2_2
            深緑の密林_2F_2_2 : 壺・樽:1個
            深緑の密林_2F_2_2 : 草:3個
            深緑の密林_2F_2_2 : 山:2個
            深緑の密林_2F_2_2 : 宝箱:1個
            深緑の密林_2F_2_2 : 冒険者:1名
            深緑の密林_2F_2_2 : ※冒険者から[バクダン]
            深緑の密林_2F_2_2 -left-> 深緑の密林_2F_3_2
            
            state "2_3" as 深緑の密林_2F_2_3
            深緑の密林_2F_2_3 : 壺・樽:3個
            深緑の密林_2F_2_3 -right-> 深緑の密林_2F_1_3
            深緑の密林_2F_2_3 -down-> 深緑の密林_2F_2_4
            深緑の密林_2F_2_3 -left[#green,thickness=5]-> 深緑の密林_2F_3_3

            state "2_4" as 深緑の密林_2F_2_4 <<Monstar>>
            深緑の密林_2F_2_4 : モンスター:4体
            深緑の密林_2F_2_4 -up-> 深緑の密林_2F_2_3
            深緑の密林_2F_2_4 -right-> 深緑の密林_2F_1_4
            深緑の密林_2F_2_4 -left-> 深緑の密林_2F_3_4

            state "3_1" as 深緑の密林_2F_3_1
            深緑の密林_2F_3_1 -up[#green,thickness=5]-> [*]
            深緑の密林_2F_3_1 -down-> 深緑の密林_2F_3_2

            state "3_2" as 深緑の密林_2F_3_2 <<Monstar>>
            深緑の密林_2F_3_2 : モンスター:4体
            深緑の密林_2F_3_2 -up[#green,thickness=5]-> 深緑の密林_2F_3_1
            深緑の密林_2F_3_2 -right-> 深緑の密林_2F_2_2
            深緑の密林_2F_3_2 -down-> 深緑の密林_2F_3_3
            深緑の密林_2F_3_2 -left-> 深緑の密林_2F_4_2

            state "3_3" as 深緑の密林_2F_3_3
            深緑の密林_2F_3_3 : 草:4個
            深緑の密林_2F_3_3 : 宝箱:1個
            深緑の密林_2F_3_3 -up[#green,thickness=5]-> 深緑の密林_2F_3_2
            深緑の密林_2F_3_3 -right-> 深緑の密林_2F_2_3

            state "3_4" as 深緑の密林_2F_3_4 <<Monstar>>
            深緑の密林_2F_3_4 : モンスター:4体

            state "4_2" as 深緑の密林_2F_4_2
            深緑の密林_2F_4_2 : 壺・樽:1個
            深緑の密林_2F_4_2 : 草:2個
            深緑の密林_2F_4_2 : 宝箱:1個
            深緑の密林_2F_4_2 : 冒険者:1名
            深緑の密林_2F_4_2 -right-> 深緑の密林_2F_3_2
        }
        深緑の密林_2F --> 深緑の密林_2.5F

        state "2.5F" as 深緑の密林_2.5F
        深緑の密林_2.5F : セーブエリア
        深緑の密林_2.5F --> 深緑の密林_3F

        state "3F" as 深緑の密林_3F {
            state "1_2" as 深緑の密林_3F_1_2 <<Start>>
            深緑の密林_3F_1_2 : スタート地点
            深緑の密林_3F_1_2 : 壺・樽:2個
            深緑の密林_3F_1_2 : 草:2個
            深緑の密林_3F_1_2 -left-> 深緑の密林_3F_2_2

            state "2_1" as 深緑の密林_3F_2_1 <<MagicShop>>
            深緑の密林_3F_2_1 : 魔導書店
            深緑の密林_3F_2_1 : 冒険者:1名

            state "2_2" as 深緑の密林_3F_2_2
            深緑の密林_3F_2_2 : 草:3個
            深緑の密林_3F_2_2 -right-> 深緑の密林_3F_1_2
            深緑の密林_3F_2_2 -down-> 深緑の密林_3F_2_3
            深緑の密林_3F_2_2 -left-> 深緑の密林_3F_3_2

            state "2_3" as 深緑の密林_3F_2_3 <<Monstar>>
            深緑の密林_3F_2_3 : モンスター:3体
            深緑の密林_3F_2_3 -up-> 深緑の密林_3F_2_2
            深緑の密林_3F_2_3 -left-> 深緑の密林_3F_3_3

            state "3_1" as 深緑の密林_3F_3_1
            深緑の密林_3F_3_1 -right-> 深緑の密林_3F_2_1
            深緑の密林_3F_3_1 -down-> 深緑の密林_3F_3_2

            state "3_2" as 深緑の密林_3F_3_2 <<Monstar>>
            深緑の密林_3F_3_2 : モンスター:4体
            深緑の密林_3F_3_2 -up-> 深緑の密林_3F_3_1
            深緑の密林_3F_3_2 -right-> 深緑の密林_3F_2_2
            深緑の密林_3F_3_2 -left-> 深緑の密林_3F_4_2

            state "3_3" as 深緑の密林_3F_3_3
            深緑の密林_3F_3_3 : 壺・樽:4個
            深緑の密林_3F_3_3 -right-> 深緑の密林_3F_2_3
            深緑の密林_3F_3_3 -down-> [*]
            深緑の密林_3F_3_3 -left-> 深緑の密林_3F_4_3

            state "4_1" as 深緑の密林_3F_4_1 <<Shop>>
            深緑の密林_3F_4_1 : ニュイ
            深緑の密林_3F_4_1 -down-> 深緑の密林_3F_4_2

            state "4_2" as 深緑の密林_3F_4_2 <<Monstar>>
            深緑の密林_3F_4_2 : モンスター:3体
            深緑の密林_3F_4_2 -up-> 深緑の密林_3F_4_1
            深緑の密林_3F_4_2 -right-> 深緑の密林_3F_3_2
            深緑の密林_3F_4_2 -down-> 深緑の密林_3F_4_3

            state "4_3" as 深緑の密林_3F_4_3 <<Monstar>>
            深緑の密林_3F_4_3 : モンスター:3体
            深緑の密林_3F_4_3 : 壺・樽:1個
            深緑の密林_3F_4_3 : ※樽から[研究日誌の紙片2]
            深緑の密林_3F_4_3 -up-> 深緑の密林_3F_4_2
            深緑の密林_3F_4_3 -right-> 深緑の密林_3F_3_3

        }
        深緑の密林_3F -down-> 深緑の密林_4F

        state 深緑の密林_4F {
            state "1_2" as 深緑の密林_4F_1_2
            深緑の密林_4F_1_2 -up-> [*]
            深緑の密林_4F_1_2 -down-> 深緑の密林_4F_1_3
            
            state "1_3" as 深緑の密林_4F_1_3 <<Monstar>>
            深緑の密林_4F_1_3 : モンスター:3体
            深緑の密林_4F_1_3 -down-> 深緑の密林_4F_1_4
            深緑の密林_4F_1_3 -left-> 深緑の密林_4F_2_3

            state "1_4" as 深緑の密林_4F_1_4
            深緑の密林_4F_1_4 : 草:13個
            深緑の密林_4F_1_4 -up-> 深緑の密林_4F_1_3

            state "2_2" as 深緑の密林_4F_2_2 <<Dummy>>
            深緑の密林_4F_2_2 -right[#white]-> 深緑の密林_4F_1_2 
            深緑の密林_4F_2_2 -down[#white]-> 深緑の密林_4F_2_3
            深緑の密林_4F_2_2 -left[#white]-> 深緑の密林_4F_3_2

            state "2_3" as 深緑の密林_4F_2_3 <<Monstar>>
            深緑の密林_4F_2_3 : モンスター:5体
            深緑の密林_4F_2_3 -right-> 深緑の密林_4F_1_3
            深緑の密林_4F_2_3 -down-> 深緑の密林_4F_2_4
            深緑の密林_4F_2_3 -left-> 深緑の密林_4F_3_3

            state "2_4" as 深緑の密林_4F_2_4
            深緑の密林_4F_2_4 : 壺・樽:3個
            深緑の密林_4F_2_4 : ※樽から[研究日誌の紙片3]
            深緑の密林_4F_2_4 : 草:2個
            深緑の密林_4F_2_4 : 山:4個
            深緑の密林_4F_2_4 -up-> 深緑の密林_4F_2_3
            深緑の密林_4F_2_4 -left-> 深緑の密林_4F_3_4

            state "3_1" as 深緑の密林_4F_3_1
            深緑の密林_4F_3_1 : 回復エリア
            深緑の密林_4F_3_1 -down-> 深緑の密林_4F_3_2

            state "3_2" as 深緑の密林_4F_3_2
            深緑の密林_4F_3_2 -up-> 深緑の密林_4F_3_1
            深緑の密林_4F_3_2 -down-> 深緑の密林_4F_3_3
            深緑の密林_4F_3_2 -left-> 深緑の密林_4F_4_2

            state "3_3" as 深緑の密林_4F_3_3 <<Monstar>>
            深緑の密林_4F_3_3 : モンスター:3体
            深緑の密林_4F_3_3 -up-> 深緑の密林_4F_3_2
            深緑の密林_4F_3_3 -right-> 深緑の密林_4F_2_3
            深緑の密林_4F_3_3 -down-> 深緑の密林_4F_3_4

            state "3_4" as 深緑の密林_4F_3_4
            深緑の密林_4F_3_4 : 壺・樽:1個
            深緑の密林_4F_3_4 : 草:1個
            深緑の密林_4F_3_4 -up-> 深緑の密林_4F_3_3
            深緑の密林_4F_3_4 -right-> 深緑の密林_4F_2_4

            state "4_2" as 深緑の密林_4F_4_2 <<Start>>
            深緑の密林_4F_4_2 : スタート地点
            深緑の密林_4F_4_2 : 草:2個
            深緑の密林_4F_4_2 -right-> 深緑の密林_4F_3_2

        }
        深緑の密林_4F -down-> 深緑の密林_5F

        state 深緑の密林_5F {
            state "1_2" as 深緑の密林_5F_1_2 <<Monstar>>
            深緑の密林_5F_1_2 : モンスター:4体
            深緑の密林_5F_1_2 : 壺・樽:1個
            深緑の密林_5F_1_2 : ※樽から[研究日誌の紙片4]
            深緑の密林_5F_1_2 -down-> 深緑の密林_5F_1_3
            深緑の密林_5F_1_2 -left-> 深緑の密林_5F_2_2

            state "1_3" as 深緑の密林_5F_1_3
            深緑の密林_5F_1_3 : 壺・樽:2個
            深緑の密林_5F_1_3 : 草:3個
            深緑の密林_5F_1_3 -up-> 深緑の密林_5F_1_2
            深緑の密林_5F_1_3 -left-> 深緑の密林_5F_2_3

            state "2_2" as 深緑の密林_5F_2_2
            深緑の密林_5F_2_2 : 壺・樽:3個
            深緑の密林_5F_2_2 -right-> 深緑の密林_5F_1_2
            深緑の密林_5F_2_2 -left-> 深緑の密林_5F_3_2

            state "2_3" as 深緑の密林_5F_2_3
            深緑の密林_5F_2_3 : 壺・樽:4個
            深緑の密林_5F_2_3 -right-> 深緑の密林_5F_1_3
            深緑の密林_5F_2_3 -left-> 深緑の密林_5F_3_3

            state "3_1" as 深緑の密林_5F_3_1
            深緑の密林_5F_3_1 -up-> [*]
            深緑の密林_5F_3_1 -down-> 深緑の密林_5F_3_2

            state "3_2" as 深緑の密林_5F_3_2 <<Monstar>>
            深緑の密林_5F_3_2 : モンスター:4体
            深緑の密林_5F_3_2 -up-> 深緑の密林_5F_3_1
            深緑の密林_5F_3_2 -right-> 深緑の密林_5F_2_2
            深緑の密林_5F_3_2 -down-> 深緑の密林_5F_3_3
            深緑の密林_5F_3_2 -left-> 深緑の密林_5F_4_2

            state "3_3" as 深緑の密林_5F_3_3 <<Monstar>>
            深緑の密林_5F_3_3 : モンスター:4体
            深緑の密林_5F_3_3 -up-> 深緑の密林_5F_3_2
            深緑の密林_5F_3_3 -right-> 深緑の密林_5F_2_3
            深緑の密林_5F_3_3 -down-> 深緑の密林_5F_3_4
            深緑の密林_5F_3_3 -left-> 深緑の密林_5F_4_3

            state "3_4" as 深緑の密林_5F_3_4 <<Start>>
            深緑の密林_5F_3_4 : スタート地点
            深緑の密林_5F_3_4 -up-> 深緑の密林_5F_3_3

            state "4_2" as 深緑の密林_5F_4_2
            深緑の密林_5F_4_2 : 壺・樽:4個
            深緑の密林_5F_4_2 -right-> 深緑の密林_5F_3_2
            深緑の密林_5F_4_2 -down-> 深緑の密林_5F_4_3

            state "4_3" as 深緑の密林_5F_4_3 <<Monstar>>
            深緑の密林_5F_4_3 : モンスター:*体
            深緑の密林_5F_4_3 -up-> 深緑の密林_5F_4_2
            深緑の密林_5F_4_3 -right-> 深緑の密林_5F_3_3

        }
        深緑の密林_5F --> 深緑の密林_5.5F
        
        state "5.5F" as 深緑の密林_5.5F
        深緑の密林_5.5F : セーブエリア
        深緑の密林_5.5F --> 深緑の密林_6F

        state "6F" as 深緑の密林_6F
        深緑の密林_6F : ボス
    }

@enduml
