@startuml MapleStory
:ログイン;
:==**準備**==
* ポイントショップからペット回収
* 薬補充
** ]
partition 絶対やりたい {
    :==**フェアリーブロのデイリークエスト**==
    --手順--
    適正レベル300体討伐
    --報酬--
    |=Item|=Comment|
    |スロット拡張|買うと高い|
    |マスタリーブックセット|買うと高い|
    ]
    note right
    end note

    partition ヴェラッドセット {
        :==**採集・採掘**==
        --おすすめ狩場--
        |=Map|=Comment|
        |ファントムフォレスト5|必ず通る|
        |迷宮4|通ったついでに|
        --手順--
        # 飽きるまで繰り返す
        ## 採る
        ## Ch変える
        --報酬--
        * 共通
        |=Item|=Priority|=Use|=Comment|
        |魔法のパウダー(**各色**)|<Color:Green>Middle</Color>|色々||
        * 採集
        |=Item|=Priority|=Use|=Comment|
        |黄昏の浄水|<Color:Red>High</Color>|色々|当たり商品|
        |ジェニファーベリーの種|<Color:Red>High</Color>|体力回復薬7000||
        |ジェニファーベリーの種のオイル|<Color:Red>High</Color>|体力回復薬7000||
        |ジェニファーベリーの花|<Color:Red>High</Color>|体力回復薬7000||
        |ジェニファーベリーの花のオイル|<Color:Red>High</Color>|体力回復薬7000||
        |ヒソップの花|<Color:Blue>Low</Color>|色々||
        |ヒソップの花のオイル|<Color:Blue>Low</Color>|色々||
        * 採掘
        |=Item|=Priority|=Use|=Comment|
        |時間の石系|<Color:Red>High</Color>|色々|当たり商品|
        |オパールの原石|<Color:Red>High</Color>|レベル1装備・アクセサリー制作|フリマで売れる|
        |オパール|<Color:Red>High</Color>|レベル1装備・アクセサリー制作|フリマで売れる|
        |銀塊の原石|<Color:Red>High</Color>|レベル1装備・アクセサリー制作|フリマで売れる|
        |銀塊|<Color:Red>High</Color>|レベル1装備・アクセサリー制作|フリマで売れる|
        |黒水晶の原石|<Color:Red>High</Color>|レベル9装備・アクセサリー制作|怪しい鉱石袋から出ない|
        |黒水晶|<Color:Red>High</Color>|レベル9装備・アクセサリー制作|怪しい鉱石袋から出ない|
        |闇のクリスタルの原石|<Color:Blue>Low</Color>|レベル9装備・アクセサリー制作||
        |闇のクリスタル|<Color:Blue>Low</Color>|レベル9装備・アクセサリー制作||
        |クリスタル(知恵)の原石|<Color:Blue>Low</Color>|レベル10装備・アクセサリー制作||
        |クリスタル(知恵)|<Color:Blue>Low</Color>|レベル10装備・アクセサリー制作||
        |クリスタル(幸運)の原石|<Color:Blue>Low</Color>|レベル10装備・アクセサリー制作||
        |クリスタル(幸運)|<Color:Blue>Low</Color>|レベル10装備・アクセサリー制作||
        |リチウムの原石|<Color:Red>High</Color>|色々||
        |リチウム|<Color:Red>High</Color>|色々||
        ]
        note right
        end note
    
        :==**ヴェラッド**==
        * 5回/日チャレンジできる
        ** 頭を倒すとその回で終わり
        --手順--
        # 左足
        # 腰
        # 右足
        # 右腕
        # 右肩
        # 左肩
        # 左腕
        # 頭(5回目のみ)
        --報酬--
        |=Item|=Enemy|=Comment|
        |パワーエリクサー|全員||
        |ヴェラッドコイン(上級)|ヴェラッドの頭|貯めよう|
        |ヴェラッドコイン(下級)|全員|貯める|
        |ハートツリー堕落の鍵|全員|集めとけ|
        --ヴェラッドコイン(下級)の使い道--
        1000枚/スタックなので、邪魔になったら使おう
        |=Name|=Comment|
        |潜在能力覚醒の書|潜在ついてない武器に|
        |疑問の**の書|低レベル武器強化に|
        --ヴェラッドコイン(上級)の使い道--
        |=Name|=Comment|
        |ヴェラッドリング(最上級)||
        |ヴェラッドイヤリング(最上級)||
        ]
        note right
        end note
    }

}

partition できればやりたい {
    :ジャクム(Normal)]
    note left
        * 強力な力の結晶
        ** 612,500メル
    end note
    note right
    end note

    partition 獅子王セット {
        :獅子王(Easy)]
        note left
            * 強力な力の結晶
            ** 1,058,000メル
        end note
        note right
        end note

        :庭師アルバイト1~3段階]
        note left
        end note
        note right
        end note
    }

    :マグナス(Easy)]
    note left
        * 強力な力の結晶
        ** 722,000メル
    end note
    note right
    end note
}

partition 暇ならやる {
    :==**専門技術の熟練度維持**==
    1日1回(?)何か作らないと経験値が減る
    --作るもの--
    |=専門技術|=Item|
    |錬金術|体力回復薬7000|
    |錬金術|マナ回復薬7000|
    |装備制作|ブランド印章|
    ]
    note right
    end note

    :==**採集・採掘**==
    --狩場--
    専門家の採取
    --報酬--
    * 採集
    |=Item|=Enemy|=Comment|
    |薬草の根|すみれ色の薬草の山||
    |ジェニファーベリーの種|すみれ色の薬草の山||
    |ジェニファーベリーの花|すみれ色の薬草の山||
    * 採掘
    |=Item|=Enemy|=Comment|
    |原石の破片|すみれ色の鉱脈||
    |リチウムの原石|すみれ色の鉱脈||
    ]
    note right
    end note
    :==**十字旅団**==]

    :バルログ]
    note right
    end note

}
:確認
* メイプルオークション
* 取り忘れ報酬
* ペット返却]

:ログアウト;
@enduml