@startuml アフターランド
    |最初の地|
    start
    |勇者ランド|
    :勇者バルログから小さい鍵入手
    後は流れで
    夜には変えない]
    |お宝ランド|
    :食べ物のカゴを70個回収する
    無限クエで使えるのでこれは売らない
    後は流れで]
    |瞑想ランド|
    :アドラーから鍵をもらう]
    |こどもランド|
    :お菓子は無限クエストに使えるので売らない
    雷が落ちた木から鍵を入手
    色を塗り終わったら無言のガキから鍵をもらう
    ブランコのガキのクエストを受託
    雨を降らせた状態にする]
    |勇者ランド|
    :戦闘の神のクエストを受託
    後は流れで]
    |お宝ランド|
    :泥棒ネズミを退治する際に無限クエストの泥棒ネズミ退治も受ける
    (受託→諦めるでガチャできる)
    他でも使うので金を6個集める
    後は流れで]
    |瞑想ランド|
    :レイヴンから鍵を取る
    色を与えた後椅子に座って鍵を取る]
    |こどもランド|
    :絵本から鍵を入手]    
    |勇者ランド|
    :昼にする
    巨大化して鍵をもらう]
    |お宝ランド|
    :マンチャから鍵を回収
    爺に石を渡す
    宙吊りの財宝のイベントを開始する
    アルマインに話した後自キャラの電球からクエストを進める必要があるので注意(良く忘れる)]
    |瞑想ランド|
    :素通り]
    |こどもランド|
    :素通り]
    |勇者ランド|
    :槍を投げる]
    |お宝ランド|
    :爺から鍵を二個もらう]
    |最初の地|
    :開封の儀式]
    end
    |水龍敬ランド|
@enduml