@startuml マガティアの錬金術師勲章
/'
:==****==
--前提条件--
* レベル:以上
* クエスト(【名前】)クリア/受注
--開始方法--
* NPC(【名前】)と会話
** 場所:【名前】
--クリア条件--
# モンスター討伐
** 【名前】:【数】
# アイテム入手
** 【名前】:【数】
*** クエスト報酬:【名前】
*** ドロップ:【名前】
*** クエスト開始時に入手
# クエストクリア
** 【名前】
# NPC(【名前】)と会話
** 場所:【名前】
--報酬--
* アイテム
** 【名前】:【数】
* 経験値:【数】
* メル:【数】
* 性向
** カリスマ:]

partition 【名前】 #ddffff {}    
'/
    start
    :==**ブローカーとの取引**==
    --前提条件--
    * レベル:以上
    * クエスト(【名前】)クリア/受注
    --開始方法--
    * NPC(【名前】)と会話
    ** 場所:【名前】
    --クリア条件--
    # モンスター討伐
    ** 【名前】:【数】
    # アイテム入手
    ** 【名前】:【数】
    *** クエスト報酬:【名前】
    *** ドロップ:【名前】
    *** クエスト開始時に入手
    # クエストクリア
    ** 【名前】
    # NPC(【名前】)と会話
    ** 場所:【名前】
    --報酬--
    * アイテム
    ** 【名前】:【数】
    * 経験値:【数】
    * メル:【数】
    * 性向
    ** カリスマ:]
    end


@enduml