@startuml 危険を追う者勲章
/'
:==****==
--前提条件--
* レベル:以上
* クエスト(【名前】)クリア/受注
--開始方法--
* NPC(【名前】)と会話
** 場所:【名前】
--クリア条件--
# モンスター討伐
** 【名前】:【数】
# アイテム入手
** 【名前】:【数】
*** クエスト報酬:【名前】
*** ドロップ:【名前】
*** クエスト開始時に入手
# クエストクリア
** 【名前】
# NPC(【名前】)と会話
** 場所:【名前】
--報酬--
* アイテム
** 【名前】:【数】
* 経験値:【数】
* メル:【数】
* 性向
** カリスマ:]
]

partition 【名前】 #ddffff {}
    
'/
    start
    fork
        :==**危険を追う者**==
        --前提条件--
        * レベル:65以上
        --開始方法--
        * NPC(クリシュラマ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # クエストクリア
        ** 取り戻した隣の彼女
        ** ドレイク完全攻略5
        ** 冒険者グウィンの日記
        ** 弟子に送る頼み
        # NPC(クリシュラマ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * アイテム
        ** 危険を追う者:1]

    fork again
        :==**ドレイク完全攻略1**==
        --前提条件--
        * レベル65以上
        --開始方法--
        * NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # モンスター討伐
        ** カッパードレイク:100
        # NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * 経験値:43,084]

        :==**ドレイク完全攻略2**==
        --前提条件--
        * レベル:65以上
        * クエスト(ドレイク完全攻略1)クリア
        --開始方法--
        * NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # モンスター討伐
        ** ドレイク:100
        # NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * 経験値:43,084]

        :==**ドレイク完全攻略3**==
        --前提条件--
        * レベル:65以上
        * クエスト(ドレイク完全攻略2)クリア
        --開始方法--
        * NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # モンスター討伐
        ** レッドドレイク:120
        # NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * 経験値:47,871]

        :==**ドレイク完全攻略4**==
        --前提条件--
        * レベル:65以上
        * クエスト(ドレイク完全攻略3)クリア
        --開始方法--
        * NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # モンスター討伐
        ** アイスドレイク:120
        # NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * 経験値:47,871]

        :==**ドレイク完全攻略5**==
        --前提条件--
        * レベル:65以上
        * クエスト(ドレイク完全攻略4)クリア
        --開始方法--
        * NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --クリア条件--
        # モンスター討伐
        ** ダークドレイク:150
        # NPC(ニッシ)と会話
        ** 場所:スリーピーウッド
        --報酬--
        * 経験値:52,658]

    fork again
        partition 超極楽おじさんの隣の彼女 #ddffff {
            :==**隣の彼女の手がかり**==
            --前提条件--
            * レベル:65以上
            --開始方法--
            * NPC(超極楽おじさん)と会話
            ** 場所:スリーピーウッド
            --クリア条件--
            * NPC(ロニ)と会話
            ** 場所:静かな湿地
            --報酬--
            * 経験値:9,574]

            :==**お腹ぺこぺこのロニ**==
            --前提条件--
            * レベル:65以上
            * クエスト(隣の彼女の手がかり)クリア
            --開始方法--
            * NPC(ロニ)と会話
            ** 場所:静かな湿地
            --クリア条件--
            # アイテム入手
            ** リナの特製ウナギ焼:1
            *** クエスト報酬:特製ウナギ焼
            ** 新鮮な牛乳:1
            *** ドロップ:カッパードレイク
            # NPC(ロニ)と会話
            ** 場所:静かな湿地
            --報酬--
            * 経験値:38,296]
        fork
        fork again
            partition 別クエスト扱い #ffffff {
                
                :==**特製ウナギ焼**==
                --前提条件--
                * レベル:65以上
                * クエスト(お腹ぺこぺこのロニ)受注
                --開始方法--
                * NPC(ホテルガイド)と会話
                ** 場所:スリーピーウッド ホテルロビー
                --クリア条件--
                # モンスター討伐
                ** カッパードレイク:50
                ** ドレイク:50
                # NPC(ホテルガイド)と会話
                ** 場所:スリーピーウッド ホテルロビー
                --報酬--
                * アイテム
                ** リナの特製ウナギ焼:1
                * 経験値:38,296]
            }
        end fork

        :==**取り戻した隣の彼女**==
        --前提条件--
        * レベル:65以上
        * クエスト(お腹ぺこぺこのロニ)クリア
        --開始方法--
        # NPC(ロニ)と会話
        ** 場所:静かな湿地
        --クリア条件--
        # アイテム入手
        ** 秘密の本:1
        *** クエスト開始時に入手
        # NPC(超極楽)と会話
        ** 場所:スリーピーウッド 回復サウナ室(<color:red><b>高級</b></color>)
        --報酬--
        * アイテム
        ** ガウン(青)/ガウン(赤):1
        * 経験値:47,871
        * メル:10,000]
        }
    fork again
        partition 怪我した冒険者 #ddffff {
            :==**ニッシの頼み**==
            --前提条件--
            * レベル:67以上
            --開始方法--
            * NPC(ニッシ)と会話
            ** 場所:スリーピーウッド
            --クリア条件--
            # アイテム入手
            ** 治療剤:1
            *** クエスト開始時に入手
            # NPC(グウィン)と会話
            ** 場所:別世界の門
            --報酬--
            * 経験値:23,935]

            :==**失くしたカバン**==
            --前提条件--
            * レベル:67以上
            * クエスト(ニッシの頼み)クリア
            --開始方法--
            * NPC(グウィン)と会話
            ** 場所:別世界の門
            --クリア条件--
            # アイテム入手
            ** グウィンのカバン:1
            *** ドロップ:ワイルドカーゴ
            # NPC(グウィン)と会話
            ** 場所:別世界の門
            --報酬--
            * 経験値:53,044]

            :==**危険な存在**==
            --前提条件--
            * レベル:67以上
            * クエスト(失くしたカバン)クリア
            --開始方法--
            * NPC(グウィン)と会話
            ** 場所:別世界の門
            --クリア条件--
            # アイテム入手
            ** 忘れられた神殿の鍵:1
            *** ドロップ:タウロマシス
            *** ドロップ:タウロスピア
            # NPC(グウィン)と会話
            ** 場所:別世界の門
            --報酬--
            * アイテム
            ** 帰還の書(スリーピー):【数】
            * 経験値:67,003]

            :==**冒険者グウィンの日記**==
            --前提条件--
            * レベル:67以上
            * クエスト(危険な存在)クリア
            --開始方法--
            * NPC(グウィン)と会話
            ** 場所:別世界の門
            --クリア条件--
            # アイテム入手
            ** グウィンの日記帳:1
            *** クエスト開始時に入手
            # NPC(ニッシ)と会話
            ** 場所:スリーピーウッド
            --報酬--
            * 経験値:23,935]

        }
    fork again
        /'多分関係ない
        partition 捨てられたメモ #ddffff {
            :==**捨てられたメモの持ち主**==
            --前提条件--
            * レベル:68以上
            --開始方法--
            * NPC(謎の紙切れ)と会話
            ** 場所:光の入らない場所
            ** 使用済みティッシュみたいな見た目のやつ
            --クリア条件--
            # NPC(ムヨン)と会話
            ** 場所:神殿の底
            --報酬--
            * 経験値:12,060]
            note right
                使用済ティッシュみたいな物
                見せられてドン引きする
                ムヨンくんかわいい
            end note
     
            :==**メモの持ち主は?**==
            --前提条件--
            * レベル:68以上
            * クエスト(捨てられたメモの持ち主)クリア
            --開始方法--
            * NPC(ムヨン)と会話
            ** 場所:神殿の底
            --クリア条件--
            # NPC(トリスタンの魂)と会話
            ** 場所:英雄の記憶
            --報酬--
            * 経験値:12,060]
        }
        '/

        partition マンジとバルログ #ddffff {
            :==**マンジの弟子**==
            --前提条件--
            * レベル:68以上
            --開始方法--
            * NPC(天地)と会話
            ** 場所:スリーピーウッド
            --クリア条件--
            # NPC(ムヨン)と会話
            ** 場所:神殿の底
            --報酬--
            * 経験値:9,045]

            :==**バルログ封印**==
            --前提条件--
            * レベル:68以上
            * クエスト(マンジの弟子)クリア
            --開始方法--
            * NPC(ムヨン)と会話
            ** 場所:神殿の底
            --クリア条件--
            # モンスター討伐
            ** 魔王バルログ:1
            # NPC(ムヨン)と会話
            ** 場所:神殿の底
            --報酬--
            * 経験値:96,484
            * メル:【数】
            * 性向
            ** カリスマ:60]

            :==**師匠に送る書札**==
            --前提条件--
            * レベル:68以上
            * クエスト(バルログ封印)クリア/受注
            --開始方法--
            * NPC(ムヨン)と会話
            ** 場所:神殿の底
            --クリア条件--
            # アイテム入手
            ** ムヨンの伝言:1
            *** クエスト開始時に入手
            # NPC(マンジ)と会話
            ** 場所:ペリオン
            --報酬--
            * 経験値:12,060]

            :==**弟子に送る頼み**==
            --前提条件--
            * レベル:68以上
            * クエスト(師匠に送る書札)クリア/受注
            --開始方法--
            * NPC(マンジ)と会話
            ** 場所:ペリオン
            --クリア条件--
            # NPC(ムヨン)と会話
            ** 場所:神殿の底
            --報酬--
            * 経験値:23,935]

        }

    end fork
    end
    note 
        多分これが一番早いと思います
        # クエスト受託
        ## 危険を追う者
        ## マンジの弟子
        ## 隣の彼女の手がかり
        ## ドレイク完全攻略1
        ## ニッシの頼み
        # クエスト(隣の彼女の手がかり)完了
        # クエスト受託
        ## お腹ぺこぺこのロニ
        ## 特製ウナギ焼
        # カッパードレイク:100体討伐&新鮮な牛乳入手
        # クエスト(ドレイク完全攻略1)完了
        # クエスト(ドレイク完全攻略2)受託
        # ドレイク:100体討伐
        # クエスト完了
        ## ドレイク完全攻略2
        ## 特製ウナギ焼
        ## お腹ぺこぺこのロニ
        # クエスト受託
        ## ドレイク完全攻略3
        ## 取り戻した隣の彼女
        # レッドドレイク:120体討伐
        # クエスト完了
        ## 取り戻した隣の彼女
        ## ドレイク完全攻略3
        # クエスト(ドレイク完全攻略4)受託
        # アイスドレイク:120体討伐
        # クエスト(ニッシの頼み)完了
        # クエスト(失くしたカバン)受託
        # グウィンのカバン:1個入手
        # クエスト(失くしたカバン)完了
        # クエスト(危険な存在)受託
        # 忘れられた神殿の鍵:1個入手
        # クエスト(危険な存在)完了
        # クエスト(冒険者グウィンの日記)受託
        # クエスト(マンジの弟子)完了
        # クエスト(バルログ封印)受託
        # バルログ:1体討伐
        # クエスト(バルログ封印)完了
        # クエスト(師匠に送る書札)受託
        # 帰還の書(ペリオン):1個購入
        # クエスト(ドレイク完全攻略4)完了
        # クエスト(ドレイク完全攻略5)受託
        # クエスト(師匠に送る書札)完了
        # クエスト(弟子に送る頼み)受託
        # クエスト(弟子に送る頼み)完了
        # ダークドレイク:150体討伐
        # クエスト(ドレイク完全攻略5)完了
        # クエスト(危険を追う者)完了
    end note

@enduml