@startuml 雪原の探検家勲章
/'
:==****==
--前提条件--
* レベル:以上
* クエスト(【名前】)クリア/受注
--開始方法--
* NPC(【名前】)と会話
** 場所:【名前】
--クリア条件--
# モンスター討伐
** 【名前】:【数】
# アイテム入手
** 【名前】:【数】
*** クエスト報酬:【名前】
*** ドロップ:【名前】
*** クエスト開始時に入手
# クエストクリア
** 【名前】
# NPC(【名前】)と会話
** 場所:【名前】
--報酬--
* アイテム
** 【名前】:【数】
* 経験値:【数】
* メル:【数】
* 性向
** カリスマ:
** 意志:]

partition 【名前】 #ddffff {}
    
'/
    start
    fork
        :==**雪原の探検家**==
        --前提条件--
        * レベル:77以上
        --開始方法--
        * NPC(アルケスタ)と会話
        ** 場所:エルナス
        --クリア条件--
        # クエストクリア
        ** アルケスタと星の石
        ** フォックス曹長の秘密
        ** 回想
        ** アルケスタのタリスマン
        # NPC(アルケスタ)と会話
        ** 場所:エルナス
        --報酬--
        * アイテム
        ** 雪原の探検家:1]

    fork again
        partition 古代の本を探して #ddffff {
            :==**「古代の本」著者の子孫**==
            --前提条件--
            * レベル:77以上
            --開始方法--
            * NPC(アルケスタ)と会話
            ** 場所:エルナス
            --クリア条件--
            # NPC(ゼイド)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:11,722]

            :==**隠された小さい墓**==
            --前提条件--
            * レベル:77以上
            * クエスト(「古代の本」著者の子孫)クリア
            --開始方法--
            * NPC(ゼイド)と会話
                ** 場所:エルナス
            --クリア条件--
            # NPC(小さな墓)と会話
            ** 場所:凍てつく野原
            --報酬--
            * 経験値:30,479]

            :==**古い指輪**==
            --前提条件--
            * レベル:77以上
            * クエスト(隠された小さい墓)クリア
            --開始方法--
            * NPC(小さな墓)と会話
            ** 場所:凍てつく野原
            --クリア条件--
            # NPC(ブラボー伍長)と会話
            ** 場所:凍てつく野原
            --報酬--
            * 経験値:11,722]

            :==**指輪の秘密**==
            --前提条件--
            * レベル:77以上
            * クエスト(古い指輪)クリア
            --開始方法--
            * NPC(ブラボー伍長)と会話
            ** 場所:凍てつく野原
            --クリア条件--
            # アイテム入手
            ** ヘクタの尻尾:100
            *** ドロップ:ヘクタ
            # NPC(ブラボー伍長)と会話
            ** 場所:凍てつく野原
            --報酬--
            * 経験値:137,155]

            :==**バラバラになった地図の欠片**==
            --前提条件--
            * レベル:77以上
            * クエスト(指輪の秘密)クリア
            --開始方法--
            * NPC(ブラボー伍長)と会話
            ** 場所:凍てつく野原
            --クリア条件--
            # アイテム入手
            ** 地図の欠片:4
            *** ドロップ:ヘクタ
            # NPC(アルケスタ)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:82,054]

            :==**完成された地図**==
            --前提条件--
            * レベル:77以上
            * クエスト(バラバラになった地図の欠片)クリア
            --開始方法--
            * NPC(アルケスタ)と会話
            ** 場所:エルナス
            --クリア条件--
            # NPC(アルケスタ)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:15,239]

            :==**石造の秘密**==
            --前提条件--
            * レベル:77以上
            * クエスト(完成された地図)クリア
            --開始方法--
            * NPC(アルケスタ)と会話
            ** 場所:エルナス
            --クリア条件--
            # アイテム入手
            ** 古い指輪:1
            *** クエスト開始時に入手
            # NPC(石像)と会話
            ** 場所:オルビス塔(8層)
            --報酬--
            * 経験値:15,239]

            :==**取り戻した古代の本**==
            --前提条件--
            * レベル:77以上
            * クエスト(石造の秘密)クリア
            --開始方法--
            * NPC(石像)と会話
            ** 場所:オルビス塔(8層)
            --クリア条件--
            # アイテム入手
            ** 古代の本:1
            *** クエスト開始時に入手
            # NPC(アルケスタ)と会話
            ** 場所:エルナス
            --報酬--
            * アイテム
            ** 守護のマント(黒):1
            * 経験値:93,056
            * 性向
            ** 意志:200]
        }

        :==**アルケスタと星の石**==
        --前提条件--
        * レベル:77以上
        * クエスト(古代の本を探して)クリア
        --開始方法--
        * NPC(アルケスタ)と会話
        ** 場所:エルナス
        --クリア条件--
        # アイテム入手
        ** 星の石:1
        *** ドロップ:ボス系モンスター
        # NPC(アルケスタ)と会話
        ** 場所:エルナス
        --報酬--
        * アイテム
        ** 魔法のマント(赤):1
        * 経験値:117,226]


    fork again
        :==**フォックス曹長の秘密**==
        --前提条件--
        * レベル:76以上
        --開始方法--
        * NPC(フォックス曹長)と会話
        ** 場所:雪で覆われた丘
        --クリア条件--
        # アイテム入手
        ** ジュニアペペの魚:50
        *** ドロップ:ジュニアペペ
        # NPC(フォックス曹長)と会話
        ** 場所:雪で覆われた丘
        --報酬--
        * 経験値:54,775]

        :==**アルケスタのマント**==
        --前提条件--
        * レベル:76以上
        * クエスト(フォックス曹長の秘密)クリア
        --開始方法--
        * NPC(アルケスタ)と会話
        ** 場所:エルナス
        --クリア条件--
        # アイテム入手
        ** ジュニアイエティの皮:50
        *** ドロップ:ジュニアイエティ
        ** ペペの口ばし:50
        *** ドロップ:ペペ
        ** ダークペペの口ばし:50
        *** ドロップ:ダークペペ
        # NPC(アルケスタ)と会話
        ** 場所:エルナス
        --報酬--
        * アイテム
        ** 温火のマント:1
        * 経験値:106,818]

    fork again
        :==**シャモスの覚醒**==
        --前提条件--
        * レベル:77以上
        --開始方法--
        * NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --クリア条件--
        # NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --報酬--
        * 経験値:21,075]

        :==**記憶の痕跡**==
        --前提条件--
        * レベル:77以上
        * クエスト(シャモスの覚醒)クリア
        --開始方法--
        * NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --クリア条件--
        # アイテム入手
        ** 記憶の日記帳5ページ:1
        *** ドロップ:※1
        ** 記憶の日記帳6ページ:1
        *** ドロップ:※1
        ** 記憶の日記帳7ページ:1
        *** ドロップ:※1
        ** 記憶の日記帳8ページ:1
        *** ドロップ:※1
        ** 記憶の日記帳9ページ:1
        *** ドロップ:※1
        # NPC(シャモス)と会話
        ** 場所:シャモスの独房
        ※1:ヘクタ,ホワイトバン
        --報酬--
        * 経験値:30,450]

        :==**シャモスの取り戻した記憶**==
        --前提条件--
        * レベル:65以上
        * クエスト(記憶の痕跡)クリア/受注
        --開始方法--
        * NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --クリア条件--
        # NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --報酬--
        * 経験値:42,150]

        :==**ホブ帝王**==
        --前提条件--
        * レベル:以上
        * クエスト(シャモスの取り戻した記憶)クリア
        --開始方法--
        * NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --クリア条件--
        # NPC(タイラス)と会話
        ** 場所:長老の宮邸
        --報酬--
        * 経験値:21,075]

        :==**回想**==
        --前提条件--
        * レベル:77以上
        * クエスト(ホブ帝王)クリア
        --開始方法--
        * NPC(ロベイラ)と会話
        ** 場所:長老の宮邸
        --クリア条件--
        # NPC(シャモス)と会話
        ** 場所:シャモスの独房
        --報酬--
        * 経験値:21,075]

    fork again
        partition 雪山の亡霊 #ddffff {
            :==**スカドルの頼み**==
            --前提条件--
            * レベル:78以上
            --開始方法--
            * NPC(スカドル)と会話
            ** 場所:エルナス
            --クリア条件--
            # アイテム入手
            ** ヘクタの尻尾:100
            *** ドロップ:ヘクタ
            ** ホワイトバンの尻尾:100
            *** ドロップ:ホワイトバン
            # NPC(スカドル)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:105,990]

            :==**スカドルの真実**==
            --前提条件--
            * レベル:78以上
            * クエスト(スカドルの頼み)クリア
            --開始方法--
            * NPC(スカドル)と会話
            ** 場所:エルナス
            --クリア条件--
            # NPC(アルケスタ)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:12,542]

            :==**雪山の亡霊**==
            --前提条件--
            * レベル:78以上
            * クエスト(スカドルの真実)クリア
            --開始方法--
            * NPC(アルケスタ)と会話
            ** 場所:エルナス
            --クリア条件--
            # アイテム入手
            ** 氷涙:1
            *** ドロップ:雪山の亡霊
            # NPC(アルケスタ)と会話
            ** 場所:エルナス
            --報酬--
            * 経験値:18,813]

            :==**アルケスタのタリスマン**==
            --前提条件--
            * レベル:78以上
            * クエスト(雪山の亡霊)クリア
            --開始方法--
            * NPC(アルケスタ)と会話
            ** 場所:エルナス
            --クリア条件--
            # アイテム入手
            ** アルケスタのタリスマン:1
            *** クエスト開始時に入手
            # NPC(スカドル)と会話
            ** 場所:エルナス
            --報酬--
            * アイテム
            ** エリクサー:30
            * 経験値:97,837]
        }


    end fork
    end
@enduml