@startuml ルイズシーカーRTA
    note top
        ざっくりチャート
        ====
        プロローグ
        ----
        ギルド初回入場時に骨針を買う
        ====
        森
        ----
        * 気合でクリア
        *バクダンをもらう
        ====
        森のローグライクダンジョン
        ----
        必須武器
        * 骨針+10
        ** 移動速度的に欲しい
        ** ここでしか稼げない
        * 武器強化するやつ
        ** 集められるだけ
        繋ぎ武器
        * 骨鎌+10
        ** +10なら強い
        * 頂点捕食者
        ** 取れるか…?
        ** 取れたら最終武器
        ====
        ラスダンまで
        ----
        最速で走り抜ける
        ====
        パーペチュアルコア
        ----
        最終武器候補
        * 聖剣クラウソラス
        **出たら強い
        * 覇道剣アレス
        **割と出る
    end note

    
@enduml
@startuml 深緑の密林
    skinparam Shadowing<<Dummy>> false
    skinparam ArrowColor<<Dummy>> white
    skinparam StateBackgroundColor<<Dummy>> white
    skinparam StateBorderColor<<Dummy>> white
    skinparam StateFontColor<<Dummy>> white

    skinparam StateBackgroundColor<<Start>> Gold
    skinparam StateBackgroundColor<<Monstar>> LightPink
    skinparam StateBackgroundColor<<MagicShop>> LightSkyBlue
    skinparam StateBackgroundColor<<Shop>> Khaki

    hide empty description
    /'
    state Name {
        state *F {
            state F_横_縦 <<Start>>
            F_横_縦 : スタート地点
            state F_横_縦 <<Monstar>>
            F_横_縦 : モンスター:*体
            state F_横_縦 <<Shop>>
            F_横_縦 : ニュイ
            state F_横_縦 <<MagicShop>>
            F_横_縦 : 魔導書店
            F_横_縦 : 壺・樽:*個
            F_横_縦 : 草:*個
            F_横_縦 : 山:*個
            F_横_縦 : 宝箱:*個
            F_横_縦 : 冒険者:*名
            F_横_縦 -up-> piyo
            F_横_縦 -right-> piyo
            F_横_縦 -down-> piyo
            F_横_縦 -left-> piyo
        }
    }
    '/
    state 深緑の密林  {
        state 1F {
            1F_1_2 : 草:2個
            1F_1_2 : 宝箱:1個
            1F_1_2 -down->1F_1_3
            1F_1_2 -left->1F_2_2

            1F_1_3 -up-> 1F_1_2
            1F_1_3 -down-> [*]
            1F_1_3 -left-> 1F_2_3

            state 1F_2_2 <<Monstar>>
            1F_2_2 : モンスター:4体
            1F_2_2 -right->1F_1_2
            1F_2_2 -down->1F_2_3
            1F_2_2 -left->1F_3_2

            1F_2_3 : 壺・樽:3個
            1F_2_3 : 草:2個
            1F_2_3 -up-> 1F_2_2
            1F_2_3 -right-> 1F_1_3
            1F_2_3 -left-> 1F_3_3

            1F_3_2 : 壺・樽:3個
            1F_3_2 : 草:4個
            1F_3_2 -right->1F_2_2
            1F_3_2 -left->1f_4_2

            state 1F_3_3 <<Monstar>>
            1F_3_3 : モンスター:4体
            1F_3_3 -right-> 1F_2_3
            1F_3_3 -down-> 1F_3_4
            1F_3_3 -left-> 1F_4_3

            1F_3_4 : 冒険者:2名
            1F_3_4 : ※冒険者から[緑のクスリ]*3
            1F_3_4 -up->1F_3_3

            state 1F_4_1 <<Start>>
            1F_4_1 : スタート地点
            1F_4_1 -down-> 1f_4_2

            state 1f_4_2 <<Monstar>>
            1f_4_2 : モンスター:3体
            1f_4_2 -up->1F_4_1
            1f_4_2 -right->1F_3_2
            1f_4_2 -down->1F_4_3

            1F_4_3 : 壺・樽:2個
            1F_4_3 : 草:1個
            1F_4_3 : 宝箱:1個
            1F_4_3 : ※空中のスイッチを押す
            1F_4_3 -up->1f_4_2
            1F_4_3 -right->1F_3_3

        }
        state 2F {
            state 2F_1_3 <<Start>>
            2F_1_3 : スタート地点
            2F_1_3 : 草:1個
            2F_1_3 -left-> 2F_2_3
            
            2F_1_4 : 壺・樽:4個
            2F_1_4 : ※壺から[研究日誌の紙片1]
            2F_1_4 : 草:2個

            2F_2_2 : 壺・樽:1個
            2F_2_2 : 草:3個
            2F_2_2 : 山:2個
            2F_2_2 : 宝箱:1個
            2F_2_2 : 冒険者:1名
            2F_2_2 : ※冒険者から[バクダン]
            2F_2_2 -left-> 2F_3_2
            
            2F_2_3 : 壺・樽:3個
            2F_2_3 -right-> 2F_1_3
            2F_2_3 -down-> 2F_2_4
            2F_2_3 -left-> 2F_3_3

            state 2F_2_4 <<Monstar>>
            2F_2_4 : モンスター:4体
            2F_2_4 -up-> 2F_2_3
            2F_2_4 -right-> 2F_1_4
            2F_2_4 -left-> 2F_3_4

            2F_3_1 -up-> [*]
            2F_3_1 -down-> 2F_3_2

            state 2F_3_2 <<Monstar>>
            2F_3_2 : モンスター:4体
            2F_3_2 -up-> 2F_3_1
            2F_3_2 -right-> 2F_2_2
            2F_3_2 -down-> 2F_3_3
            2F_3_2 -left-> 2F_4_2

            2F_3_3 : 草:4個
            2F_3_3 : 宝箱:1個
            2F_3_3 -up-> 2F_3_2
            2F_3_3 -right-> 2F_2_3

            state 2F_3_4 <<Monstar>>
            2F_3_4 : モンスター:4体

            2F_4_2 : 壺・樽:1個
            2F_4_2 : 草:2個
            2F_4_2 : 宝箱:1個
            2F_4_2 : 冒険者:1名
            2F_4_2 -right-> 2F_3_2
        }
        --
        2.5F : セーブエリア
        --
        state 3F {
            state 3F_1_2 <<Start>>
            3F_1_2 : スタート地点
            3F_1_2 : 壺・樽:2個
            3F_1_2 : 草:2個
            3F_1_2 -left-> 3F_2_2

            3F_2_2 : 草:3個
            3F_2_2 -right-> 3F_1_2
            3F_2_2 -down-> 3F_2_3
            3F_2_2 -left-> 3F_3_2

            state 3F_3_2 <<Monstar>>
            3F_3_2 : モンスター:4体
            3F_3_2 -up-> 3F_3_1
            3F_3_2 -right-> 3F_2_2
            3F_3_2 -left-> 3F_4_2

            3F_3_1 -right-> 3F_2_1
            3F_3_1 -down-> 3F_3_2

            state 3F_2_1 <<MagicShop>>
            3F_2_1 : 魔導書店
            3F_2_1 : 冒険者:1名

            state 3F_4_2 <<Monstar>>
            3F_4_2 : モンスター:3体
            3F_4_2 -up-> 3F_4_1
            3F_4_2 -right-> 3F_3_2
            3F_4_2 -down-> 3F_4_3

            state 3F_4_1 <<Shop>>
            3F_4_1 : ニュイ
            3F_4_1 -down-> 3F_4_2

            state 3F_4_3 <<Monstar>>
            3F_4_3 : モンスター:3体
            3F_4_3 : 壺・樽:1個
            3F_4_3 : ※樽から[研究日誌の紙片2]
            3F_4_3 -up-> 3F_4_2
            3F_4_3 -right-> 3F_3_3

            3F_3_3 : 壺・樽:4個
            3F_3_3 -right-> 3F_2_3
            3F_3_3 -down-> [*]
            3F_3_3 -left-> 3F_4_3

            state 3F_2_3 <<Monstar>>
            3F_2_3 : モンスター:3体
            3F_2_3 -up-> 3F_2_2
            3F_2_3 -left-> 3F_3_3
        }
        state 4F {
            4F_1_2 -up-> [*]
            4F_1_2 -down-> 4F_1_3
            
            state 4F_1_3 <<Monstar>>
            4F_1_3 : モンスター:3体
            4F_1_3 -down-> 4F_1_4
            4F_1_3 -left-> 4F_2_3

            4F_1_4 : 草:13個
            4F_1_4 -up-> 4F_1_3

            state 4F_2_2 <<Dummy>>
            4F_2_2 -right[#white]-> 4F_1_2 
            4F_2_2 -down[#white]-> 4F_2_3
            4F_2_2 -left[#white]-> 4F_3_2

            state 4F_2_3 <<Monstar>>
            4F_2_3 : モンスター:5体
            4F_2_3 -right-> 4F_1_3
            4F_2_3 -down-> 4F_2_4
            4F_2_3 -left-> 4F_3_3

            4F_2_4 : 壺・樽:3個
            4F_2_4 : ※樽から[研究日誌の紙片3]
            4F_2_4 : 草:2個
            4F_2_4 : 山:4個
            4F_2_4 -up-> 4F_2_3
            4F_2_4 -left-> 4F_3_4

            4F_3_1 : 回復エリア
            4F_3_1 -down-> 4F_3_2

            4F_3_2 -up-> 4F_3_1
            4F_3_2 -down-> 4F_3_3
            4F_3_2 -left-> 4F_4_2

            state 4F_3_3 <<Monstar>>
            4F_3_3 : モンスター:3体
            4F_3_3 -up-> 4F_3_2
            4F_3_3 -right-> 4F_2_3
            4F_3_3 -down-> 4F_3_4

            4F_3_4 : 壺・樽:1個
            4F_3_4 : 草:1個
            4F_3_4 -up-> 4F_3_3
            4F_3_4 -right-> 4F_2_4

            state 4F_4_2 <<Start>>
            4F_4_2 : スタート地点
            4F_4_2 : 草:2個
            4F_4_2 -right-> 4F_3_2

        }
        state 5F {
            state 5F_1_2 <<Monstar>>
            5F_1_2 : モンスター:4体
            5F_1_2 : 壺・樽:1個
            5F_1_2 : ※樽から[研究日誌の紙片4]
            5F_1_2 -down-> 5F_1_3
            5F_1_2 -left-> 5F_2_2

            5F_1_3 : 壺・樽:2個
            5F_1_3 : 草:3個
            5F_1_3 -up-> 5F_1_2
            5F_1_3 -left-> 5F_2_3

            5F_2_2 : 壺・樽:3個
            5F_2_2 -right-> 5F_1_2
            5F_2_2 -left-> 5F_3_2

            5F_2_3 : 壺・樽:4個
            5F_2_3 -right-> 5F_1_3
            5F_2_3 -left-> 5F_3_3

            5F_3_1 -up-> [*]
            5F_3_1 -down-> 5F_3_2

            state 5F_3_2 <<Monstar>>
            5F_3_2 : モンスター:4体
            5F_3_2 -up-> 5F_3_1
            5F_3_2 -right-> 5F_2_2
            5F_3_2 -down-> 5F_3_3
            5F_3_2 -left-> 5F_4_2

            state 5F_3_3 <<Monstar>>
            5F_3_3 : モンスター:4体
            5F_3_3 -up-> 5F_3_2
            5F_3_3 -right-> 5F_2_3
            5F_3_3 -down-> 5F_3_4
            5F_3_3 -left-> 5F_4_3

            state 5F_3_4 <<Start>>
            5F_3_4 : スタート地点
            5F_3_4 -up-> 5F_3_3

            5F_4_2 : 壺・樽:4個
            5F_4_2 -right-> 5F_3_2
            5F_4_2 -down-> 5F_4_3

            state 5F_4_3 <<Monstar>>
            5F_4_3 : モンスター:*体
            5F_4_3 -up-> 5F_4_2
            5F_4_3 -right-> 5F_3_3

        }
        --
        5.5F : セーブエリア
        --
        最深層 : ボス
    }

@enduml
@startuml 汚泥奈落
    skinparam Shadowing<<Dummy>> false
    skinparam ArrowColor<<Dummy>> white
    skinparam StateBackgroundColor<<Dummy>> white
    skinparam StateBorderColor<<Dummy>> white
    skinparam StateFontColor<<Dummy>> white

    skinparam StateBackgroundColor<<Start>> Gold
    skinparam StateBackgroundColor<<Monstar>> LightPink
    skinparam StateBackgroundColor<<MagicShop>> LightSkyBlue
    skinparam StateBackgroundColor<<Shop>> Khaki

    hide empty description
    /'
    state Name {
        state *F {
            state F_横_縦 <<Start>>
            F_横_縦 : スタート地点
            state F_横_縦 <<Monstar>>
            F_横_縦 : モンスター:*体
            state F_横_縦 <<Shop>>
            F_横_縦 : ニュイ
            state F_横_縦 <<MagicShop>>
            F_横_縦 : 魔導書店
            F_横_縦 : 壺・樽:*個
            F_横_縦 : 草:*個
            F_横_縦 : 山:*個
            F_横_縦 : 宝箱:*個
            F_横_縦 : 冒険者:*名
            F_横_縦 -up-> piyo
            F_横_縦 -right-> piyo
            F_横_縦 -down-> piyo
            F_横_縦 -left-> piyo
        }
    }
    '/
    hide empty description
    state 汚泥奈落 {
        state 1F {
            1F_1_1 : スタート地点
            1F_1_1 : 壺・樽:2個
            1F_1_1 -left-> 1F_2_1

            1F_1_2 : 草:4個
            1F_1_2 -right-> [*]
            1F_1_2 -down-> 1F_1_3
            1F_1_2 -left-> 1F_2_2

            1F_1_3 : モンスター:3体
            1F_1_3 -up-> 1F_1_2
            1F_1_3 -left-> 1F_2_3
            
            1F_2_1 : モンスター:3体
            1F_2_1 -right-> 1F_1_1
            1F_2_1 -down-> 1F_2_2

            1F_2_2 : モンスター:3体
            1F_2_2 -up-> 1F_2_1
            1F_2_2 -right-> 1F_1_2
            1F_2_2 -left-> 1F_3_2

            1F_2_3 : 草:4個
            1F_2_3 -right-> 1F_1_3
            1F_2_3 -down-> 1F_2_4
            1F_2_3 -left-> 1F_3_3

            1F_2_4 : 壺・樽:2個
            1F_2_4 : 草:2個
            1F_2_4 : 冒険者:1名
            1F_2_4 -up-> 1F_2_3
            1F_2_4 -left-> 1F_3_4

            1F_3_2 : 壺・樽:2個
            1F_3_2 -right-> 1F_2_2
            1F_3_2 -down-> 1F_3_3

            1F_3_3 : モンスター:4体
            1F_3_3 : バイスから[赤のクスリ]
            1F_3_3 -up-> 1F_3_2
            1F_3_3 -right-> 1F_2_3
            1F_3_3 -down-> 1F_3_4

            1F_3_4 : 壺・樽:2個
            1F_3_4 -up-> 1F_3_3
            1F_3_4 -right-> 1F_2_4

        }
        state 2F {
            2F_1_1 : モンスター:4体
            2F_1_1 -down-> 2F_1_2
            2F_1_1 -left-> 2F_2_1

            2F_1_2 : 草:2個
            2F_1_2 -up-> 2F_1_1
            2F_1_2 -left-> 2F_2_2

            2F_2_1 : 壺・樽:2個
            2F_2_1 : 草:1個
            2F_2_1 : 宝箱:1個
            2F_2_1 -right-> 2F_1_1
            2F_2_1 -down-> 2F_2_2

            2F_2_2 : モンスター:4体
            2F_2_2 : 草:3個
            2F_2_2 -up-> 2F_2_1
            2F_2_2 -right-> 2F_1_2
            2F_2_2 -down-> 2F_2_3
            2F_2_2 -left-> 2F_3_2

            2F_2_3 -up-> 2F_2_2
            2F_2_3 -right-> [*]
            2F_2_3 -down-> 2F_2_4

            2F_2_4 : モンスター:4体
            2F_2_4 -up-> 2F_2_3
            2F_2_4 -left-> 2F_3_4

            2F_3_1 : スタート地点
            2F_3_1 -down-> 2F_3_2

            2F_3_2 : モンスター:3体
            2F_3_2 : 草:2個
            2F_3_2 -up-> 2F_3_1
            2F_3_2 -right-> 2F_2_2
            2F_3_2 -down-> 2F_3_3

            2F_3_3 -up-> 2F_3_2
            2F_3_3 -down-> 2F_3_4

            2F_3_4 : 魔導書店
            2F_3_4 -up-> 2F_3_3
            2F_3_4 -right-> 2F_2_4

        }
        state 3F {
            3F_1_3 : モンスター:4体
            3F_1_3 -up-> 3F_1_2
            3F_1_3 -down-> 3F_1_4
            3F_1_3 -left-> 3F_2_3

            3F_1_4 : モンスター:3体
            3F_1_4 -up-> 3F_1_3
            3F_1_4 -left-> 3F_2_4

            3F_2_3 : 壺・樽:3個
            3F_2_3 : 草:2個
            3F_2_3 -up-> [*]
            3F_2_3 -right-> 3F_1_3

            3F_2_4 -right-> 3F_1_4
            3F_2_4 -left-> 3F_3_4

            3F_3_2 : スタート地点
            3F_3_2 : 壺・樽:2個
            3F_3_2 : 草:11個
            3F_3_2 : 宝箱:1個
            3F_3_2 -down-> 3F_3_3

            3F_3_3 : 壺・樽:4個
            3F_3_3 : 冒険者:3名
            3F_3_3 -up-> 3F_3_2
            3F_3_3 -down-> 3F_3_4
            3F_3_3 -left-> 3F_4_3

            3F_3_4 : 壺・樽:2個
            3F_3_4 : 草:2個
            3F_3_4 -up-> 3F_3_3
            3F_3_4 -right-> 3F_2_4
            3F_3_4 -left-> 3F_4_4

            3F_4_3 : モンスター:3体
            3F_4_3 -right-> 3F_3_3
            3F_4_3 -down-> 3F_4_4

            3F_4_4 : モンスター:4体
            3F_4_4 -up-> 3F_4_3
            3F_4_4 -right-> 3F_3_4
        }
        --
        3.5F : セーブエリア
        --
        state 4F {
            4F_1_1 : 壺・樽:2個
            4F_1_1 : ニュイ
            4F_1_1 -left-> 4F_2_1

            4F_1_3 : 壺・樽:5個
            4F_1_3 : ※バクダン稼ぎするならここ
            4F_1_3 : 草:5個
            4F_1_3 -left-> 4F_2_3

            4F_2_1 : モンスター:5体
            4F_2_1 : ※バイスから[赤いクスリ]
            4F_2_1 -right-> 4F_1_1
            4F_2_1 -down-> 4F_2_2
            4F_2_1 -left-> 4F_3_1

            4F_2_2 : モンスター:4体
            4F_2_2 -up-> 4F_2_1
            4F_2_2 -down-> 4F_2_3
            4F_2_2 -left-> 4F_3_2

            4F_2_3 : モンスター:4体
            4F_2_3 -up-> 4F_2_2
            4F_2_3 -right-> 4F_1_3
            4F_2_3 -down-> 4F_2_4

            4F_2_4 : 壺・樽:2個
            4F_2_4 : 草:2個
            4F_2_4 -up-> 4F_2_3
            4F_2_4 -left-> 4F_3_4

            4F_3_1 : 壺・樽:2個
            4F_3_1 : 草:2個
            4F_3_1 -right-> 4F_2_1
            4F_3_1 -left-> [*]

            4F_3_2 : モンスター:4体
            4F_3_2 : 草:2個
            4F_3_2 -right-> 4F_2_2
            4F_3_2 -left-> 4F_4_2

            4F_3_4 : モンスター:4体
            4F_3_4 -right-> 4F_2_4

            4F_4_2 : スタート地点
            4F_4_2 : 壺・樽:2個
            4F_4_2 -right-> 4F_3_2
            
        }
        --
        4.5F : セーブエリア(リバストン)
        --
        state 5F {
            5F_1_2 : 壺・樽:3個
            5F_1_2 -down-> 5F_1_3

            5F_1_3 : モンスター:4体
            5F_1_3 -up-> 5F_1_2
            5F_1_3 -down-> 5F_1_4
            5F_1_3 -left-> 5F_2_3

            5F_1_4 : 壺・樽:4個
            5F_1_4 -up-> 5F_1_3
            5F_1_4 -down-> [*]

            5F_2_1 : モンスター:3体
            5F_2_1 : 壺・樽:2個
            5F_2_1 -left-> 5F_3_1

            5F_2_3 : 壺・樽:4個
            5F_2_3 : ヌイ族:1匹
            5F_2_3 : ※ヌイ族に[ヌイまんじゅう]を渡すと
            5F_2_3 : 　[聖窪の種火]入手
            5F_2_3 -right-> 5F_1_3
            5F_2_3 -left-> 5F_3_3

            5F_3_1 : ニュイ
            5F_3_1 -right-> 5F_2_1
            5F_3_1 -down-> 5F_3_2

            5F_3_2 : 冒険者:1名
            5F_3_2 -up-> 5F_3_1
            5F_3_2 -down-> 5F_3_3
            
            5F_3_3 : モンスター:3体
            5F_3_3 -up-> 5F_3_2
            5F_3_3 -right-> 5F_2_3
            5F_3_3 -down-> 5F_3_4

            5F_3_4 : モンスター:3体
            5F_3_4 -up-> 5F_3_3
            5F_3_4 -left-> 5F_4_4

            5F_4_4 : スタート地点
            5F_4_4 : 壺・樽:2個
            5F_4_4 -right-> 5F_3_4

        }
        state 6F {
            6F_3_1 : スタート地点
            6F_3_1 : 壺・樽:3個
            6F_3_1 : 草:2個
            6F_3_1 -down-> 6F_3_2

            6F_3_2 : モンスター:4体
            6F_3_2 -up-> 6F_3_1
            6F_3_2 -down-> 6F_3_3

            6F_3_3 : 壺・樽:2個
            6F_3_3 : 草:2個
            6F_3_3 -up-> 6F_3_2
            6F_3_3 -right-> 6F_2_3
            6F_3_3 -left-> 6F_4_3

            6F_4_3 : モンスター:4体
            6F_4_3 -right-> 6F_3_3

            6F_2_3 : 草:2個
            6F_2_3 : 冒険者:2名
            6F_2_3 -down-> 6F_2_4
            6F_2_3 -left-> 6F_3_3

            6F_2_4 : モンスター:4体
            6F_2_4 -up-> 6F_2_3
            6F_2_4 -right-> 6F_1_4
            6F_2_4 -left-> 6F_3_4

            6F_3_4 : モンスター:4体
            6F_3_4 : 壺・樽:2個
            6F_3_4 -right-> 6F_2_4

            6F_1_4 : 壺・樽:5個
            6F_1_4 : 草:3個
            6F_1_4 -up-> 6F_1_3
            6F_1_4 -left-> 6F_2_4

            6F_1_3 : モンスター:4体
            6F_1_3 -up-> 6F_1_2
            6F_1_3 -down-> 6F_1_4

            6F_1_2 -up-> [*]
            6F_1_2 -down-> 6F_1_3

            6F_4_4 : 成形用ダミー
            6F_4_4 -up-> 6F_4_3
            6F_4_4 -right-> 6F_3_4

        }
    }
@enduml